version: '3.4'
services:
  freespace:
    build: .
    ports: 
      - 8080:8080
    image: "${REGISTRY_NAME}devclubiitd/freespace:0.1"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
    networks:
      - "reverseproxy"


networks:
  reverseproxy:
    external:
      name: "reverseproxy"